persistence:
  # type: file # memory, file, redis, etc.
  # options:
  #   dirs-path: ./data/persistence
    
  type : memory # Use in-memory persistence for simplicity

max-retry: 3 # Maximum number of retries for message processing
retry-interval: 3s # Interval between retries
lease-duration: 3s # Duration for message lease
debug: true # Enable debug mode

http:
  enabled: true
  port: 8080
  rate:
    limit: 1
    burst: 5
  auth:
    api_key: ${API_KEY}

grpc:
  enabled: true
  port: 50051
  auth:
    api_key: ${API_KEY}